name: Build redocly etc files
on: 
  push:
    branches:
      - main # mainへのプッシュ（PRのマージでも）でワークフローを実行する
jobs:
  run-redocly-cli:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Install Redocly CLI
        run: |
          npm install -g @redocly/cli@latest
      - name: Run build-redoc-html
        run: npx redocly build-docs document/swagger.yml --output=document/openapi.html
      - name: Run build-redocly-mockdata
        run: npx redocly bundle document/swagger.yml --output ./src/mocks/openapi.json
      # TODO : openapi-typescriptのスキーマ定義も自動生成したい
      # - name: Run generate:openapi
      #   run: npx openapi-typescript document/swagger.yml -o ./src/shared/api/v1.schema.ts
      # TODO : msw-auto-mockも自動生成したい
      # - name: Run generate:mock
      #   run: npx msw-auto-mock document/swagger.yml -o ./src/mocks
      # ###################
      # workflowページからZIPでダウンロード可能になる。お客さんに展開する時、便利だな。
      # ###################
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: redocly-html
      #     path: output/redocly-static.html
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Update redoc document
          ref: ${{ github.head_ref }}
